### ISSUE TITLE
Hiking Lesson 

### ISSUE THREAD

**Issue by reishun** [sharpobject/sgre#59]
It looks like it buffs not debuff

Hiking Lesson
All Followers on the enemy Field get STA decreased by the total SIZE of your Field divided by the number of cards on your Field (rounding down).
]]
[200302] = function(player, opponent)
  local mag = floor(player:field_size() / (#player.field - #player:empty_field_slots()))
  local idxs = opponent:field_idxs_with_preds(pred.follower)
  local buff = OnePlayerBuff(opponent)
  for _, idx in ipairs(idxs) do
    buff[idx] = {sta={"-",mag}}
  end
  buff:apply()
end,

**Comment by sharpobject** [comment]
This is fixed.
