### ISSUE TITLE
Child Iri bugged

### ISSUE THREAD

**Issue by reishun** [sharpobject/sgre#60]
Turn Start: A random Follower on the enemy Field gets ATK -1/STA -2. If the number of cards in your Hand is even, it gets an additional DEF -1.

  if #player.hand % 2 == 0 then
    local target = uniformly(opponent:field_idxs_with_preds(pred.follower))
    if target then
      OneBuff(opponent, target, {atk={"-",1},def={"-",1},sta={"-",1}}):apply()
    end
  end
end,

**Comment by sharpobject** [comment]
This is fixed.
